/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __ooi_detection_t_hpp__
#define __ooi_detection_t_hpp__



class ooi_detection_t
{
    public:
        int64_t    utime;
        double     xy[2];
        int8_t     type;

    public:
        static const int8_t   TYPE_STATIC = 0x00;
        static const int8_t   TYPE_MOBILE = 0x01;
        static const int8_t   TYPE_CIVILIAN = 0x02;
        static const int8_t   TYPE_JUDGE = 0x03;
        static const int8_t   TYPE_CAR = 0x04;
        static const int8_t   TYPE_ENTRANCE = 0x05;
        static const int8_t   TYPE_TOXIC_VAT = 0x06;
        static const int8_t   TYPE_STATIONARY_MOBILE = 0x07;
        static const int8_t   TYPE_ORSC = 0x08;
        static const int8_t   TYPE_ORSC_CHEST = 0x09;
        static const int8_t   TYPE_ORSC_CAN = 0x0a;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int ooi_detection_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ooi_detection_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ooi_detection_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ooi_detection_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ooi_detection_t::getTypeName()
{
    return "ooi_detection_t";
}

int ooi_detection_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->xy[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ooi_detection_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->utime, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->xy[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ooi_detection_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 2);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    return enc_size;
}

int64_t ooi_detection_t::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0xe868645c53795a76LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
