/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __ooi_detection_list_t_hpp__
#define __ooi_detection_list_t_hpp__

#include <vector>
#include "ooi_detection_t.hpp"


class ooi_detection_list_t
{
    public:
        int16_t    ndetections;
        std::vector< ooi_detection_t > detections;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int ooi_detection_list_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ooi_detection_list_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ooi_detection_list_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ooi_detection_list_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ooi_detection_list_t::getTypeName()
{
    return "ooi_detection_list_t";
}

int ooi_detection_list_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->ndetections, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->ndetections; a0++) {
        tlen = this->detections[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int ooi_detection_list_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->ndetections, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->detections.resize(this->ndetections);
    for (int a0 = 0; a0 < this->ndetections; a0++) {
        tlen = this->detections[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int ooi_detection_list_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->ndetections; a0++) {
        enc_size += this->detections[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t ooi_detection_list_t::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ooi_detection_list_t::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)ooi_detection_list_t::getHash };

    int64_t hash = 0xb500ae1d322891dcLL +
         ooi_detection_t::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
